package com.sandrew.boot.mapper;

import com.sandrew.boot.model.TmFunctionPO;
import com.sandrew.boot.model.TmFunctionPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmFunctionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    long countByExample(TmFunctionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByExample(TmFunctionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insert(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insertSelective(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    List<TmFunctionPO> selectByExample(TmFunctionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    TmFunctionPO selectByPrimaryKey(Integer functionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") TmFunctionPO record, @Param("example") TmFunctionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExample(@Param("record") TmFunctionPO record, @Param("example") TmFunctionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKeySelective(TmFunctionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_function
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKey(TmFunctionPO record);
}