package com.sandrew.boot.mapper;

import com.sandrew.boot.model.TmRolePO;
import com.sandrew.boot.model.TmRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    long countByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insert(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insertSelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    List<TmRolePO> selectByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    TmRolePO selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExample(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKeySelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKey(TmRolePO record);
}