package com.sandrew.boot.mapper;

import com.sandrew.boot.model.TtSessionPO;
import com.sandrew.boot.model.TtSessionPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtSessionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    long countByExample(TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByExample(TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insert(TtSessionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int insertSelective(TtSessionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    List<TtSessionPO> selectByExampleWithBLOBs(TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    List<TtSessionPO> selectByExample(TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    TtSessionPO selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") TtSessionPO record, @Param("example") TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TtSessionPO record, @Param("example") TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByExample(@Param("record") TtSessionPO record, @Param("example") TtSessionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKeySelective(TtSessionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TtSessionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_session
     *
     * @mbg.generated Mon Oct 29 13:03:11 CST 2018
     */
    int updateByPrimaryKey(TtSessionPO record);
}