package com.sandrew.bootcas.mapper;

import com.sandrew.bootcas.model.TmFuncFront;
import com.sandrew.bootcas.model.TmFuncFrontExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmFuncFrontMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    long countByExample(TmFuncFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int deleteByExample(TmFuncFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int deleteByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int insert(TmFuncFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int insertSelective(TmFuncFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    List<TmFuncFront> selectByExample(TmFuncFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    TmFuncFront selectByPrimaryKey(Integer funcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") TmFuncFront record, @Param("example") TmFuncFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByExample(@Param("record") TmFuncFront record, @Param("example") TmFuncFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByPrimaryKeySelective(TmFuncFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByPrimaryKey(TmFuncFront record);
}