package com.sandrew.bootcas.mapper;

import com.sandrew.bootcas.model.TmUserPO;
import com.sandrew.bootcas.model.TmUserPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmUserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    long countByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int deleteByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int insert(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int insertSelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    List<TmUserPO> selectByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    TmUserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByExample(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByPrimaryKeySelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Tue Jul 28 14:06:48 CST 2020
     */
    int updateByPrimaryKey(TmUserPO record);
}