package com.sandrew.mvc.mapper;

import com.sandrew.mvc.model.TrUserRolePO;
import com.sandrew.mvc.model.TrUserRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrUserRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    long countByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int deleteByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int insert(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int insertSelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    List<TrUserRolePO> selectByExample(TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    TrUserRolePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int updateByExample(@Param("record") TrUserRolePO record, @Param("example") TrUserRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int updateByPrimaryKeySelective(TrUserRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_user_role
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    int updateByPrimaryKey(TrUserRolePO record);
}