package com.sandrew.boot.model;

import java.io.Serializable;
import java.util.Date;

public class TmFuncFront implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.func_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer funcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.role_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.path
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.name
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.title
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.file
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.icon
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.redirect
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private String redirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.father_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.is_delete
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.create_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.create_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.update_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_func_front.update_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_func_front
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.func_id
     *
     * @return the value of tm_func_front.func_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.func_id
     *
     * @param funcId the value for tm_func_front.func_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.role_id
     *
     * @return the value of tm_func_front.role_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.role_id
     *
     * @param roleId the value for tm_func_front.role_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.path
     *
     * @return the value of tm_func_front.path
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.path
     *
     * @param path the value for tm_func_front.path
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.name
     *
     * @return the value of tm_func_front.name
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.name
     *
     * @param name the value for tm_func_front.name
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.title
     *
     * @return the value of tm_func_front.title
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.title
     *
     * @param title the value for tm_func_front.title
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.file
     *
     * @return the value of tm_func_front.file
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.file
     *
     * @param file the value for tm_func_front.file
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.icon
     *
     * @return the value of tm_func_front.icon
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.icon
     *
     * @param icon the value for tm_func_front.icon
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.redirect
     *
     * @return the value of tm_func_front.redirect
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public String getRedirect() {
        return redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.redirect
     *
     * @param redirect the value for tm_func_front.redirect
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setRedirect(String redirect) {
        this.redirect = redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.father_id
     *
     * @return the value of tm_func_front.father_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.father_id
     *
     * @param fatherId the value for tm_func_front.father_id
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setFatherId(Integer fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.is_delete
     *
     * @return the value of tm_func_front.is_delete
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.is_delete
     *
     * @param isDelete the value for tm_func_front.is_delete
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.create_by
     *
     * @return the value of tm_func_front.create_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.create_by
     *
     * @param createBy the value for tm_func_front.create_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.create_date
     *
     * @return the value of tm_func_front.create_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.create_date
     *
     * @param createDate the value for tm_func_front.create_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.update_by
     *
     * @return the value of tm_func_front.update_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.update_by
     *
     * @param updateBy the value for tm_func_front.update_by
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_func_front.update_date
     *
     * @return the value of tm_func_front.update_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_func_front.update_date
     *
     * @param updateDate the value for tm_func_front.update_date
     *
     * @mbg.generated Tue Feb 04 14:47:55 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}