package com.sandrew.boot.model;

import java.io.Serializable;
import java.util.Date;

public class TrRoleFuncFront implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.role_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.function_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Integer functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.create_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.create_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.update_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func_front.update_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tr_role_func_front
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.id
     *
     * @return the value of tr_role_func_front.id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.id
     *
     * @param id the value for tr_role_func_front.id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.role_id
     *
     * @return the value of tr_role_func_front.role_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.role_id
     *
     * @param roleId the value for tr_role_func_front.role_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.function_id
     *
     * @return the value of tr_role_func_front.function_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.function_id
     *
     * @param functionId the value for tr_role_func_front.function_id
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.create_by
     *
     * @return the value of tr_role_func_front.create_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.create_by
     *
     * @param createBy the value for tr_role_func_front.create_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.create_date
     *
     * @return the value of tr_role_func_front.create_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.create_date
     *
     * @param createDate the value for tr_role_func_front.create_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.update_by
     *
     * @return the value of tr_role_func_front.update_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.update_by
     *
     * @param updateBy the value for tr_role_func_front.update_by
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func_front.update_date
     *
     * @return the value of tr_role_func_front.update_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func_front.update_date
     *
     * @param updateDate the value for tr_role_func_front.update_date
     *
     * @mbg.generated Sun Feb 02 18:57:45 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}