package com.sandrew.mvc.model;

import java.util.Date;

public class TrRoleFuncPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.role_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.function_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Integer functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.create_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.create_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.update_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_role_func.update_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.id
     *
     * @return the value of tr_role_func.id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.id
     *
     * @param id the value for tr_role_func.id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.role_id
     *
     * @return the value of tr_role_func.role_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.role_id
     *
     * @param roleId the value for tr_role_func.role_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.function_id
     *
     * @return the value of tr_role_func.function_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.function_id
     *
     * @param functionId the value for tr_role_func.function_id
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.create_by
     *
     * @return the value of tr_role_func.create_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.create_by
     *
     * @param createBy the value for tr_role_func.create_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.create_date
     *
     * @return the value of tr_role_func.create_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.create_date
     *
     * @param createDate the value for tr_role_func.create_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.update_by
     *
     * @return the value of tr_role_func.update_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.update_by
     *
     * @param updateBy the value for tr_role_func.update_by
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_role_func.update_date
     *
     * @return the value of tr_role_func.update_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_role_func.update_date
     *
     * @param updateDate the value for tr_role_func.update_date
     *
     * @mbg.generated Fri Oct 19 15:30:36 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}